//
// Created by Ervin Bosenbacher on 13/06/2021.
//

#ifndef UNTITLED_LOCKVALIDATINGDIRECTORYWRAPPER_H
#define UNTITLED_LOCKVALIDATINGDIRECTORYWRAPPER_H


class LockValidatingDirectoryWrapper {

};


#endif //UNTITLED_LOCKVALIDATINGDIRECTORYWRAPPER_H
