//
// Created by Ervin Bosenbacher on 13/06/2021.
//

#ifndef UNTITLED_SINGLEINSTANCELOCKFACTORY_H
#define UNTITLED_SINGLEINSTANCELOCKFACTORY_H


class SingleInstanceLockFactory {

};


#endif //UNTITLED_SINGLEINSTANCELOCKFACTORY_H
